cors:
    originPatterns: http://localhost:3000,http://localhost:8080,https://localhost:8080
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    url: jdbc:h2:mem:projetolista
    driverClassName: org.h2.Driver
    username: sa
    password: password
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
        path: /h2-console
springdoc:
  paths-to-match:
      - /auth/**
      - /api/**/v1/**
  swagger-ui:
    use-root-path: true
